example_project/articles/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import ArticlesView, ArticleDetailView, ArticleCreateView

urlpatterns = (
    url('^$', ArticlesView.as_view(), name='articles'),
    url('^create/$', ArticleCreateView.as_view(), name='create'),
    url('^(?P<pk>[0-9]+)/$', ArticleDetailView.as_view(), name='article'),
)

example_project/example_project/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic import TemplateView
from articles import urls

from .views import IsAuthenticated, OnlyPOSTRequest, NonExistentURL

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name="base.html"), name='home'),
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'logout.html'}, name='logout'),
    url(r'^is_authenticated/$', IsAuthenticated.as_view(),
        name='is_authenticated'),
    url(r'^only_post_request/$', OnlyPOSTRequest.as_view(),
        name='only_post_request'),
    url(r'^non_existent_url/$', NonExistentURL.as_view(),
        name='non_existent_url'),
    url(r'^articles/', include(urls, namespace='articles'))
]

example_project/articles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class Article(models.Model):
    headline = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    published = models.BooleanField(default=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def __unicode__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('articles:article', kwargs={'pk': self.pk})

example_project/core/models.py
from django.db import models

# Create your models here.

example_project/articles/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, CreateView

from .models import Article


class ArticlesView(ListView):
    model = Article
    template_name = 'articles.html'
    context_object_name = 'articles'
    queryset = Article.objects.filter(published=True)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article.html'

    def get_object(self, queryset=None):
        article = super(ArticleDetailView, self).get_object(queryset)
        if not article.published and article.owner != self.request.user:
            raise Http404()
        return article


class ArticleCreateView(CreateView):
    model = Article
    fields = ('headline', 'description')
    template_name = 'article_form.html'

example_project/example_project/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseNotFound
from django.views.generic import View, TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class LoginRequiredMixin(object):
    @method_decorator(login_required(login_url=reverse_lazy('login')))
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(
            request, *args, **kwargs)


class IsAuthenticated(LoginRequiredMixin, TemplateView):

    def get(self, request, *args, **kwargs):
        return HttpResponse()


class OnlyPOSTRequest(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        return HttpResponse()


class NonExistentURL(View):

    def get(self, request, *args, **kwargs):
        return HttpResponseNotFound()

    def post(self, request, *args, **kwargs):
        return HttpResponseNotFound()

example_project/templates/article.html
{% extends 'articles.html' %}

{% block content %}
    <h1>{{ article.headline }}</h1>
    <p>{{ article.description }}</p>
{% endblock content %}

example_project/templates/article_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create article</h1>
    <form method="POST" action="{% url 'articles:create' %}">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit"/>
    </form>
{% endblock content %}

example_project/templates/articles.html
{% extends 'base.html' %}

{% block content %}
    <h1>Articles</h1>
    {% for article in articles %}
        <li>
            <a href="{% url 'articles:article' article.pk %}">{{ article.pk }} {{ article}}</a>
        </li>
    {% endfor %}
{% endblock content %}

example_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% if user.is_authenticated %}
    <p>
        Welcome, {{ user.get_username }}. Thanks for logging in.
        <a href="{% url 'logout' %}">Log out.</a>
    </p>
{% else %}
    <p>Welcome, new user. Please <a href="{% url 'login' %}">log in</a>.</p>
{% endif %}
{% block content %}
    <h1>SteelKiwi Dev.</h1>
{% endblock content %}
</body>
</html>

example_project/templates/login.html
{% extends "base.html" %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="/" />
    </form>
{% endblock %}

example_project/templates/logout.html
{% extends "base.html" %}

{% block content %}
    <h1>Good buy!</h1>
{% endblock %}